# Generated by Django 3.2.13 on 2022-06-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactform_options'),
    ]

    operations = [
        migrations.RenameModel('ContactForm', 'Contact'),
    ]
